// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: author_address.sql

package db

import (
	"context"
)

const createAuthorAddress = `-- name: CreateAuthorAddress :one
insert into author_address (
    address_line_one,
    city,
    state,
    country,
    author_id
) values (
    $1,$2,$3,$4,$5
) RETURNING id, address_line_one, city, state, country, author_id, created_at
`

type CreateAuthorAddressParams struct {
	AddressLineOne string `json:"address_line_one"`
	City           string `json:"city"`
	State          string `json:"state"`
	Country        string `json:"country"`
	AuthorID       int64  `json:"author_id"`
}

func (q *Queries) CreateAuthorAddress(ctx context.Context, arg CreateAuthorAddressParams) (AuthorAddress, error) {
	row := q.db.QueryRowContext(ctx, createAuthorAddress,
		arg.AddressLineOne,
		arg.City,
		arg.State,
		arg.Country,
		arg.AuthorID,
	)
	var i AuthorAddress
	err := row.Scan(
		&i.ID,
		&i.AddressLineOne,
		&i.City,
		&i.State,
		&i.Country,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}
