// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Author struct {
	ID            int64     `json:"id"`
	AuthorName    string    `json:"author_name"`
	AuthorAddress string    `json:"author_address"`
	CreatedAt     time.Time `json:"created_at"`
}

type AuthorAddress struct {
	ID             int64     `json:"id"`
	AddressLineOne string    `json:"address_line_one"`
	City           string    `json:"city"`
	State          string    `json:"state"`
	Country        string    `json:"country"`
	AuthorID       int64     `json:"author_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Book struct {
	ID          int64          `json:"id"`
	BookName    string         `json:"book_name"`
	BookDesc    string         `json:"book_desc"`
	AuthorID    int64          `json:"author_id"`
	ForThis     sql.NullString `json:"for_this"`
	PublishDate time.Time      `json:"publish_date"`
	CreatedAt   time.Time      `json:"created_at"`
}

type BookManagment struct {
	ID            int64     `json:"id"`
	BookID        int64     `json:"book_id"`
	TotalQuantity int32     `json:"total_quantity"`
	TotalInLab    int32     `json:"total_in_lab"`
	TotalOutLab   int32     `json:"total_out_lab"`
	CreatedAt     time.Time `json:"created_at"`
}

type UserBooks struct {
	ID             int64        `json:"id"`
	UserID         int64        `json:"user_id"`
	BookID         int64        `json:"book_id"`
	CreatedAt      time.Time    `json:"created_at"`
	PurchaseDate   sql.NullTime `json:"purchase_date"`
	BookReturnDate sql.NullTime `json:"book_return_date"`
}

type Users struct {
	ID           int64     `json:"id"`
	UserName     string    `json:"user_name"`
	UserEmail    string    `json:"user_email"`
	UserPassword string    `json:"user_password"`
	CreatedAt    time.Time `json:"created_at"`
}
